### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by performanceArtist** [DaRkLoL1/Fullstack-Development-2-task#14]
Сейчас каждый компонент написан функцией, которая в некоторых случаях(к примеру с dropdown.js) получается довольно громоздкой. Это всё лучше заменить на js-классы, чтобы потом уже для каждого найденного по селектору элемента создавать свой инстанс. Такой подход позволит разделить функционал по методам и сделать код более читаемым.

**Comment by performanceArtist** [comment]
Также надобности в iife особо не будет, т.к. всё будет в пределах класса. Кстати вызов и создание инстансов надо сделать отдельно - рядом положить файл init.js, например. Чтобы если ты захотел этот класс импортировать и переиспользовать в другом компоненте тебе не пришлось бы убирать эти вызовы.

**Comment by DaRkLoL1** [comment]
Но это же вроде создаст глобальные переменные, или это не важно?

**Comment by performanceArtist** [comment]
Не создаст, т.к. webpack все модули(файлы с кодом) оборачивает - они доступны только при импорте. Можешь даже попробовать в другом файле вызвать класс - не получится.

**Comment by performanceArtist** [comment]
datepicker.createDatepicker();
  datepicker.addButtons();
Такие методы по идее можно в конструкторе вызывать, чтобы каждый раз потом не вспоминать, что нужно вызвать после создания инстанса.

**Comment by performanceArtist** [comment]
`const $item = $(this.item); `

Если у тебя что-то повторяется между методами, лучше это повесить на this. И item - очень общее название, лучше пересмотреть.

**Comment by performanceArtist** [comment]
```
      onSelect(formattedDate) {
        const arrDates = formattedDate.split(',');
```

Обработчики надо выносить в методы.

**Comment by performanceArtist** [comment]
Также следует придерживаться принципа разделения ответственности: каждый метод должен делать что-то одно. Можно разделить поиск по dom и навешивание событий, вынести логику по выбору даты(if (Array.isArray(dates))...).

**Comment by performanceArtist** [comment]
И сделай все блоки классами - пускай они и мелкие. Так всё равно проще понять, что происходит.

**Comment by performanceArtist** [comment]
Ещё заметил, что у тебя будто Datepicker используется несколько раз, но в отдельную сущность не выделен.

**Comment by performanceArtist** [comment]
```
      if (sliderItem.length > 3) {
        const lengthSlice = sliderItem.length - 3;
        sliderItem = `${sliderItem.slice(0, lengthSlice)} ${sliderItem.slice(lengthSlice)}`;
      }
```

Тут можно проще сделать, без условий - почитай про slice.

**Comment by performanceArtist** [comment]
Какой смысл в классах, если у тебя все методы static? Я имел в виду сделать аналогично другим.

**Comment by performanceArtist** [comment]
Ещё в calendar.js c 21 строки начинает большой кусок кода, который лучше как-нибудь разбить по методам.

**Comment by performanceArtist** [comment]
Почему switch написан иначе, чем остальные классы? Притом поиск элементов почему-то производится в обработчике события, хотя достаточно было бы их выбрать один раз.

**Comment by performanceArtist** [comment]
val, obj - сокращать имена не надо, obj можно лучше назвать. По названию должно быть понятно, что это.

**Comment by performanceArtist** [comment]
С like-button аналогично switch - непонятно, зачем делать выборку элементов внутри обработчика события.

**Comment by performanceArtist** [comment]
handleChekcbox - опечатка.

**Comment by performanceArtist** [comment]
handleButtonsClick в dropdown.js будто не нужен.

**Comment by performanceArtist** [comment]
В calendar.js this.param не надо перезначать, если он дальше не используется. Также нужно назвать иначе - это по сути у тебя дефолтные значения, не зависимые от конкретного инстанса. Object.assign лучше заменить на spread - это короче и не будет менять оригинальный объект, как у тебя сейчас.

**Comment by performanceArtist** [comment]
`while (Number.parseInt(this.$dropdown.find('.counter').text(), 10) !== 0)` - подобные конструкции использовать не надо - это не очевидно и не надёжно.

**Comment by performanceArtist** [comment]
`$clearButton.on(`click.clearButton${this.index}``
`addClass('datepicker_width_266');`

Странные события/классы. Можешь объяснить, зачем?

**Comment by performanceArtist** [comment]
В чём смысл лупов, которые сбрасывают значения? Нельзя просто поменять его, без имитации нажатия на кнопку? Лишнее усложение только.

**Comment by performanceArtist** [comment]
`$button.addClass('button-zero');`
`& button.button-decrement.button-zero `

Не по методологии совершенно. Такое надо модификаторами разруливать.

**Comment by DaRkLoL1** [comment]
`$clearButton.on(`click.clearButton${this.index}`
 `addClass('datepicker_width_266');`
 Странные события/классы. Можешь объяснить, зачем?

clearButton кнопка для очистки (сброса) выбранных дат 
addClass задает ширину календаря

**Comment by DaRkLoL1** [comment]
> В чём смысл лупов, которые сбрасывают значения? Нельзя просто поменять его, без имитации нажатия на кнопку? Лишнее усложение только.

Никак не поменяешь, только так можно. Плагин эти значения хранит в замыкании, в объекте. Доступ к ним только через события увеличить/уменьшить на один. Вот и приходится имитировать нажатие кнопок.

**Comment by Nelliza** [comment]
**expandable-checkbox-list.js**
![1](https://user-images.githubusercontent.com/19621113/71060499-b7b26200-2176-11ea-9d0c-a0f5aba231b5.png)

Вот этот метод следует оптимизировать, избавившись от условного оператора и заменив `addClass()` / `removeClass()` на `toggleClass()`

**Comment by Nelliza** [comment]
По коду в **field-button.js** тоже много вопросов:

1. Почему название компонента и файла с классом - `field-button`, а сам класс при этом называется `field`?
2. Название метода `createField()` не соответствует функционалу - в нем ты по идее кэшируешь выбранные из DOM-дерева элементы в переменные + навешиваешь на них обработчики событий, никаких полей ты не создаешь, это инициализационный метод, логичнее назвать его например `initFieldButton()`
3. Для чего назначение обработчиков событий разбросано по 4-м разным методам, когда их можно все объединить в один? Т.е. по идее в методе `initFieldButton()` ты инициализируешь поля `this.$fieldButton` и `this.$textField` и вызываешь метод, навешивающий обработчики событий, и все, так намного проще и читабельнее получается

**Comment by Nelliza** [comment]
Первый пункт предыдущего коммента по именованию классов касается также классов `CheckboxList`, `Like` и `Mask`

**Comment by Nelliza** [comment]
По поводу названия инициализационного метода также посмотри пожалуйста везде по проекту - почти все классы с аналогичным именованием `create-` вместо `init-`
