### ISSUE TITLE
Навигация по страницам

### ISSUE THREAD

**Issue by performanceArtist** [DaRkLoL1/Fullstack-Development-2-task#16]
Она сейчас не работает ни на github pages, ни в проекте. Нужно нормально включить её в проект - чтобы при запуске он её сразу отображал и можно было бы легко открыть страницы.

**Comment by performanceArtist** [comment]
Поправь ещё в конфиге, чтобы сразу переходило на неё, убери вертикальный скролл, и можешь закрывать.

**Comment by Nelliza** [comment]
В твоем проекте при клике на кнопки "Войти", "Зарегистрироваться", "Подобрать номер" ничего не происходит, хотя макетом предусмотрены отдельные страницы под эти действия, т.е. по идее эти кнопки должны быть ссылками на другие страницы сайта.

Было бы круто еще при нажатии на эту карточку реализовать переход на страницу **Room details**, таким образом навигация покрыла бы все страницы сайта, но это по желанию, думаю )
![5](https://user-images.githubusercontent.com/19621113/69803140-4e30da80-11ec-11ea-91ac-a4da6b879a36.png)
