### ISSUE TITLE
Ссылка на gh-pages нерабочая

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#18]

**Comment by DaRkLoL1** [comment]
ее удалить чтоль?

**Comment by Nelliza** [comment]
Нет, заменить на рабочую )

**Comment by DaRkLoL1** [comment]
Как? мне же написали, добавить папку dist в gitignore

**Comment by Nelliza** [comment]
Я решала с помощью плагина gh-pages, там вроде несложно настраивается
