### ISSUE TITLE
Кодстайл

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#19]
Мелкие правки по code style:

**button.pug**
![1](https://user-images.githubusercontent.com/19621113/68673586-25121800-0565-11ea-8cbf-bea1762f321d.png)
Здесь можно упростить записи, присваивая результаты работы тернарного оператора сразу при объявлении переменных.

**room.pug**
![2](https://user-images.githubusercontent.com/19621113/68675926-fc405180-0569-11ea-8457-93be8dc4431c.png)
Вот здесь в [стайлгайде от airbnb](https://github.com/airbnb/javascript#variables--unary-increment-decrement) не рекомендуется использовать инкремент/декремент, заменив их записью вида `num += 1`.

**room-booking.pug**
![3](https://user-images.githubusercontent.com/19621113/68675918-f8acca80-0569-11ea-9097-760edabb05d2.png)
Проверки с 2 и более условиями должны быть вынесены ([п. 7 наших стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/ec7dee976ddedd308454f9a3c5ccb766aba1302e/JS/goodPractice.md))
То же самое в **dropdown.js**, посмотри плиз и там )

**Comment by Nelliza** [comment]
Исправь опечатку плиз в файле **block-head.pug** в метатеге description

**Comment by DaRkLoL1** [comment]
исправил

**Comment by Nelliza** [comment]
**elements.pug**
![1](https://user-images.githubusercontent.com/19621113/70836236-a54fc580-1e10-11ea-9504-538e1ea696e3.png)
При передаче в качестве аргумента объекта со множеством ключей целесообразнее отбивать каждый новый ключ переносом строки в целях увеличения читаемости кода. Посмотри и исправь плиз и в других местах проекта

**Comment by Nelliza** [comment]
Инклуды отбивай плиз пустой строкой, у тебя не везде так

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/71058646-913df800-2171-11ea-9e2c-c94380655114.png)

Инклуды отбивай плиз пустой строкой, у тебя не везде отбиты

**Comment by Nelliza** [comment]
**bullet-list.scss**
![2](https://user-images.githubusercontent.com/19621113/71058726-d104df80-2171-11ea-8e98-23fb2db2de1e.png)

Вот здесь тоже нужно привести к единообразию: убрать лишнюю пустую строку перед последней фигурной скобкой и добавить между псевдоклассом / псевдоэлементом

**Comment by Nelliza** [comment]
В **checkbox-list.scss** еще посмотри внизу

**Comment by Nelliza** [comment]
**dropdown.pug**
![1](https://user-images.githubusercontent.com/19621113/71323644-642d7480-24e6-11ea-9ee7-d89b693b1e74.png)

Здесь будет гораздо компактнее и читабельнее, если ты массив присвоишь `arrDefaultNumbers` сразу по дефолту при деструктуризации объекта с опциями

И убери плиз лишние запятую с пробелом перед закрывающей фигурной скобкой там же

**Comment by Nelliza** [comment]
**room-details.pug**
![1](https://user-images.githubusercontent.com/19621113/71323747-be7b0500-24e7-11ea-8c8a-7b005085f995.png)

Согласно [стайлгайду от Airbnb](https://github.com/airbnb/javascript#es6-template-literals), следует использовать шаблонные строки вместо конкатенации. Посмотри пожалуйста везде по проекту

**Comment by Nelliza** [comment]
Еще все декларации импортов должны быть размещены в самом верху файлов

**Comment by DaRkLoL1** [comment]
> Еще все декларации импортов должны быть размещены в самом верху файлов

Ты про include в pug-файлах?

**Comment by Nelliza** [comment]
> Ты про include в pug-файлах?

Да
