### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#21]
Выложи плиз изображения, по которым подгонялся PerfectPixel, и скрин с его настройками

**Comment by DaRkLoL1** [comment]
я их удалил

**Comment by Nelliza** [comment]
Почему?

**Comment by DaRkLoL1** [comment]
https://www.figma.com/file/MumYcKVk9RkKZEG6dR5E3A/FSD-education-program.-The-2nd-task
вот отсюда скачивал
Да зачем мне этот хлам хранить)

**Comment by DaRkLoL1** [comment]
А что мне тут делать?

**Comment by Nelliza** [comment]
Пока ничего, но я ишью не закрываю, т.к. есть несовпадения с макетом, которые чуть позже соберу и обрисую здесь

**Comment by Nelliza** [comment]
Pixel Perfect показывает большие расхождения с макетом (
Выложи плиз скрины страниц с наложенными слоями Pixel Perfect, чтобы окошко настроек Pixel Perfect при этом было открытым

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-24 17_22_22](https://user-images.githubusercontent.com/32780725/69496072-0b66be00-0edf-11ea-9a31-335c4cbd321a.png)

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-24 17_30_20](https://user-images.githubusercontent.com/32780725/69496156-2128b300-0ee0-11ea-9d64-5580a84df053.png)

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-24 17_37_42](https://user-images.githubusercontent.com/32780725/69496248-2cc8a980-0ee1-11ea-895a-41955da2ec3c.png)

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-24 17_39_52](https://user-images.githubusercontent.com/32780725/69496278-8a5cf600-0ee1-11ea-99e4-d3a836bc882e.png)

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-24 17_44_02](https://user-images.githubusercontent.com/32780725/69496321-12430000-0ee2-11ea-84c2-94825fa71d1a.png)

**Comment by Nelliza** [comment]
Соврала, расхождения не особо большие ) Только в **Form Elements** много расхождений, но я не уверена, что в UI-kit требуется точное соблюдение PixelPerfect. Подправь пока вот эти моменты, ок?
![1](https://user-images.githubusercontent.com/19621113/69800701-d7dda980-11e6-11ea-9396-57f14e121d64.png)
![2](https://user-images.githubusercontent.com/19621113/69800722-de6c2100-11e6-11ea-9332-c2fa796f9c11.png)
![3](https://user-images.githubusercontent.com/19621113/69800726-e0ce7b00-11e6-11ea-9f2d-c22f30d5c003.png)

**Comment by Nelliza** [comment]
Еще нюанс, давай здесь же исправим: на небольших разрешениях экрана навигационное меню смотрится не совсем корректно: 
![4](https://user-images.githubusercontent.com/19621113/69801799-212ef880-11e9-11ea-9689-50e4b891c202.png)

Предлагаю исправить это добавлением паддингов пунктам меню. И по вертикали тоже они у тебя не выровнены, выглядит не очень эстетично, откорректируй плиз и это )

**Comment by DaRkLoL1** [comment]
![](https://user-images.githubusercontent.com/19621113/69800701-d7dda980-11e6-11ea-9396-57f14e121d64.png)
в Ui-Kit и Pages между списками разное расстояние, я не смог сделать идеально. Мне забить на UI-kit и сделать ток для Pages?

**Comment by Nelliza** [comment]
Да, думаю на UI-kit можно забить, т.к. основная цель все же сверстать аккуратно сами страницы )

**Comment by Nelliza** [comment]
**Form Elements**

Кнопки слетели:
![1](https://user-images.githubusercontent.com/19621113/70171994-e04f4c00-16e0-11ea-96ed-7f46606de117.png)

**Comment by DaRkLoL1** [comment]
ты про большую кнопку чтоль?

**Comment by Nelliza** [comment]
Нет, про расстояния между кнопками/ссылками
