### ISSUE TITLE
Использовать везде двойные кавычки для значений атрибутов

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#22]
У тебя много где в коде используются одинарные кавычки в значениях атрибутов вперемешку с двойными, приведи плиз к единому стилю.

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/69004655-10989b80-0928-11ea-879d-ee80eebd33bd.png)
Значения атрибутов миксинов я тоже имела в виду )
Вообще в html/pug принято использовать везде двойные кавычки, за исключением разве что случаев использования шаблонных строк

**Comment by Nelliza** [comment]
Думаю, можно сразу в этом же ишью исправить двойные кавычки на одинарные в **fonts.scss**

**Comment by DaRkLoL1** [comment]
а JS код с одинарными оставить?

**Comment by Nelliza** [comment]
Да, в JS и CSS одинарные используются

**Comment by DaRkLoL1** [comment]
я имел ввиду js в Pug файлах

**Comment by Nelliza** [comment]
В pug везде двойные кавычки, кроме шаблонных строк. Ты одним махом через Ctrl+F меняешь и все )
