### ISSUE TITLE
Перевести px в rem

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#23]
Для адаптивной верстки удобно использовать `rem` -  в медиазапросе меняешь только размер шрифта корневого элемента -> остальные размеры меняются пропорционально. Плюс это правило есть в [css-стандартах - п. 5](https://github.com/fullstack-development/front-end-best-practices/blob/99766f0d4d37ed8e0529f6e5d34a76f62d1071d9/CSS/fonts.md).
Чтобы не мучиться с изменением размеров вручную, можно воспользоваться расширением px to rem. Точно знаю, что для VSCode оно есть, только что проверила ) Пользоваться удобно -  выделяешь нужную строчку или само значение, либо сразу весь код, и нажимаешь _Alt+Z_.

**Comment by DaRkLoL1** [comment]
Вообще все px чтоль? Я думал это для шрифта ток

**Comment by Nelliza** [comment]
Да, тут имелись в виду размеры в том числе и элементов, не только размеры шрифта:
> На **элементах** без специфичных требований (не фиксированные пиксели и не относительно области экрана) использовать rem, изучить по максимуму чем отличаются px, pt, em, rem, vh, vw, vmin, vmax и их использовать в остальных случаях; ([п. 5 CSS-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/99766f0d4d37ed8e0529f6e5d34a76f62d1071d9/CSS/fonts.md))

**Comment by Nelliza** [comment]
В файле **colors-types.scss** еще остались

**Comment by Nelliza** [comment]
Теперь в **elements.scss** и **datepicker.scss** еще появились
