### ISSUE TITLE
Стилизация в JS

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#24]
**calendar.js**
![2](https://user-images.githubusercontent.com/19621113/69004901-307d8e80-092b-11ea-8ce0-b7b7ccebb6e7.png)
Стилизацию в JS следует задавать через переключение классов/модификаторов вместо прямого воздействия на свойство `style`. Исключение могут составлять случаи, когда заранее вычислить нужное значение невозможно, и оно будет вычисляться только в процессе работы скрипта.

**Comment by DaRkLoL1** [comment]
.datepicker это класс плагина в нем для всех других календарей уже стоит width 320px , другого способа задать width для FilterDatepicker я не нашел

**Comment by Nelliza** [comment]
Предлагаю альтернативный способ - т.к. в стилевых файлах должны содержаться только стили, относящиеся к самому блоку, думаю, лучшим вариантом будет создать директорию vendor, а в ней файл стилей (можешь назвать его например datepicker-ui.scss), содержащий переопределяющее значение ширины. Только не забудь, что значение задаем не в пикселях. Если возникнут какие-то трудности - задавай вопросы )

**Comment by Nelliza** [comment]
Предлагаю альтернативный способ - т.к. в стилевых файлах должны содержаться только стили, относящиеся к самому блоку, думаю, лучшим вариантом будет создать директорию vendor, а в ней файл стилей (можешь назвать его например datepicker-ui.scss), содержащий переопределяющее значение ширины. Только не забудь, что значение задаем не в пикселях. Если возникнут какие-то трудности - задавай вопросы )

**Comment by Nelliza** [comment]
Предлагаю альтернативный способ - т.к. в стилевых файлах должны содержаться только стили, относящиеся к самому блоку, думаю, лучшим вариантом будет создать директорию vendor, а в ней файл стилей (можешь назвать его например _datepicker-ui.scss_), содержащий переопределяющее значение ширины. Только не забудь, что значение задаем не в пикселях. Если возникнут какие-то трудности - задавай вопросы )

**Comment by Nelliza** [comment]
Предлагаю альтернативный способ - т.к. в стилевых файлах должны содержаться только стили, относящиеся к самому блоку, думаю, лучшим вариантом будет создать директорию _vendor_, а в ней файл стилей (можешь назвать его например _datepicker-ui.scss_), содержащий переопределяющее значение ширины. Только не забудь, что значение задаем не в пикселях. Если возникнут какие-то трудности - задавай вопросы )

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-19 12_58_53](https://user-images.githubusercontent.com/32780725/69136711-64dc8080-0acc-11ea-84d4-8758e9ac254a.png)
datepicker.scss уже лежит в папке calendar)

**Comment by Nelliza** [comment]
Его надо вынести из директории компонента во внешнюю папку (_vendor_) и там уже прописать тот стиль, который тебе нужен. Вообще по структуре проекта будет отдельное ишью, но, думаю, лучше файл _datepicker.scss_ сразу в рамках этого ишью перенести

**Comment by DaRkLoL1** [comment]
Так в нем и прописано 320px(

**Comment by Nelliza** [comment]
Давай подумаем: там есть общие стили для блока календаря, и если тебе нужно слегка видоизменить стиль одного из экземпляров этого блока, какую БЭМ-сущность ты будешь использовать?

**Comment by DaRkLoL1** [comment]
Так это стили плагина, в нем никакого БЕМа нет

**Comment by Nelliza** [comment]
Это-то понятно, но тебе же ничего не мешает добавить к блоку плагина модификатор для изменения ширины одного из календарей, вместо того чтобы напрямую воздействовать на свойство `style` )

**Comment by DaRkLoL1** [comment]
Да, но это найти и добавить стиль скриптом, вроде проще изменить style

**Comment by Nelliza** [comment]
А что там искать? В выделенной строчке вместо метода `css()` используешь метод `addClass()` для добавления модификатора, и плюс в стилях добавляешь правило для этого модификатора, и все )
