### ISSUE TITLE
Разделение зависимостей в package.json

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#25]
Нужно откорректировать разделение зависимостей на devDependencies и dependencies: в devDependencies ты должен оставить только те зависимости, которые тебе нужны исключительно в режиме разработки, и при отсутствии которых можно все равно без проблем собрать проект.
Если что, задавай вопросы, подробнее отвечу )

**Comment by Nelliza** [comment]
По факту у тебя в devDependencies должен остаться минимум пакетов: литер и все, что с ним связано, вебпаковские cli и dev-server, ну и плагин gh-pages

**Comment by Nelliza** [comment]
По факту у тебя в devDependencies должен остаться минимум пакетов: литер и все, что с ним связано, вебпаковские cli и dev-server, ну и плагин gh-pages. Чтобы те, кому нужно только собрать проект без его разработки, не устанавливали лишние пакеты, которые никак не влияют на конечный продукт.

**Comment by Nelliza** [comment]
Да

**Comment by DaRkLoL1** [comment]
Хорошо сделал. Ток я не понял зачем это?

**Comment by Nelliza** [comment]
Имелось в виду убрать из дева и перенести в dependencies )

**Comment by Nelliza** [comment]
Имелось в виду убрать из дева и перенести в dependencies, а не вообще выпилить )
