### ISSUE TITLE
Поля формы

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#26]
Для полей форм с четким предназначением следует использовать соответствующие типы, в том числе html5-типы: `email`, `password`, `date`, `tel` и т.д. ([п. 21 html-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/2555d6f787b2467ade9353a1278894667c1aefb5/HTML/tags.md)).

**Comment by Nelliza** [comment]
Не везде исправил: на странице **Form Elements** и в футере еще остались неуказанные типы

**Comment by Nelliza** [comment]
Еще здесь же сразу отмечу, что все интерактивные элементы должны находиться внутри тега `<form>`, посмотри панель фильтра номеров и форму подписки в футере, ну и в целом по проекту, может еще где встретишь

**Comment by Nelliza** [comment]
Еще момент - на главной странице в форме подбора номера нелогичное заполнение полей диапазона даты: при выборе первого значения оно почему-то записывается в правое поле, и только потом при задании диапазона все встает на свои места, пофиксь плиз и это тоже

**Comment by DaRkLoL1** [comment]
Насчет оборачивания в form. Нужно ли оборачивать кнопки в header, список комнат со звездами, и комменты с лайками?

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-19 12_43_15](https://user-images.githubusercontent.com/32780725/69135474-33fb4c00-0aca-11ea-9bec-4481e260227c.png)
В макете так нарисовано

**Comment by Nelliza** [comment]
> Насчет оборачивания в form. Нужно ли оборачивать кнопки в header, список комнат со звездами, и комменты с лайками?

Нет, в хедере у тебя это обычные кнопки с типом `button`, они не отправляют данных, которые можно было бы обернуть в форму (тип `submit`). Вообще по идее эти элементы должны быть реализованы не кнопками, а ссылками на другие страницы для возможности навигации по сайту. Этот момент я хотела уточнить, нужно тебе править или нет. Давай я тогда уточню сегодня, и если что создам отдельное ишью для этого.

Суть в том, что тут имелись ввиду именно интерактивные элементы управления **формы**, т.е. текстовые поля, флажки, переключатели, выпадающие списки, кнопки отправки.

**Comment by Nelliza** [comment]
> Насчет оборачивания в form. Нужно ли оборачивать кнопки в header, список комнат со звездами, и комменты с лайками?

Нет, в хедере у тебя это обычные кнопки с типом button, они не отправляют данных, которые можно было бы обернуть в форму (тип submit). Вообще по идее эти элементы должны быть реализованы не кнопками, а ссылками на другие страницы для возможности навигации по сайту. Этот момент я хотела уточнить, нужно тебе править или нет. Давай я тогда уточню сегодня, и если что создам отдельное ишью для этого.

Суть в том, что тут имелись в виду именно интерактивные элементы управления формы, т.е. текстовые поля, флажки, переключатели, выпадающие списки, кнопки отправки.

**Comment by Nelliza** [comment]
> ![Скриншот 2019-11-19 12_43_15](https://user-images.githubusercontent.com/32780725/69135474-33fb4c00-0aca-11ea-9bec-4481e260227c.png)
> В макете так нарисовано

В макете просто прорисовано для наглядности 2 различных состояния элемента: по умолчанию и с уже выбранной датой

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/69301608-e4cb2d80-0c27-11ea-9c48-c1ac67ddcce0.png)
Еще момент: ты зря здесь поменял тип на `date`, т.к. нам макет подсказывает, что это _masked text field_, т.е. текстовое поле с маской ввода. В компоненте регистрации аналогично

**Comment by DaRkLoL1** [comment]
Тогда макет вводит в заблуждение))

**Comment by Nelliza** [comment]
Еще небольшие нюансы:

- в форме подписки по логике должна быть кнопка отправки email, роль которой выполняет стрелочка, а то не семантично получается;

- обнаружен баг маски при вводе единицы в качестве первой цифры месяца рождения:
![1](https://user-images.githubusercontent.com/19621113/69430706-446c2a80-0d47-11ea-97af-0a1c0ff12296.gif)

PS. Интересная у тебя возрастная дискриминация получается в маске - для людей старше 70 лет услуги отеля недоступны )

**Comment by DaRkLoL1** [comment]
PS. Интересная у тебя возрастная дискриминация получается в маске - для людей старше 70 лет услуги отеля недоступны ) 
Ну да смешно вышло))
