### ISSUE TITLE
Изображения

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#27]
**header.pug**
![3](https://user-images.githubusercontent.com/19621113/69005332-d3d1a200-0931-11ea-9746-dc6192f80318.png)
Здесь отсутствует обязательный атрибут `alt` у тега `img`

**Comment by Nelliza** [comment]
Все изображения также нужно оптимизировать, об этом [тут](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/includeFiles.md) (п. 4). Можно воспользоваться пакетом image-webpack-loader, как вариант

**Comment by Nelliza** [comment]
Изображения, относящиеся к конкретным компонентам, следует разложить внутри директорий images этих компонентов. А те изображения, которые используются в нескольких местах на сайте (например, лого), складываются в общую для всего проекта папку images.

**Comment by DaRkLoL1** [comment]
т.е создать внутри компонента папку images и кинуть туда картинки?

**Comment by Nelliza** [comment]
Да, внутри всех содержащих изображения компонентов создать такие папки, и плюс внутри src папку для общих изображений
