### ISSUE TITLE
Навигация по сайту ч.2

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#28]
В твоем проекте при клике на кнопки "Войти", "Зарегистрироваться", "Подобрать номер" ничего не происходит, хотя макетом предусмотрены отдельные страницы под эти действия, т.е. по идее эти кнопки должны быть ссылками на другие страницы сайта.

Было бы круто еще при нажатии на эту карточку реализовать переход на страницу **Room details**, таким образом навигация покрыла бы все страницы сайта, но это по желанию, думаю )
![5](https://user-images.githubusercontent.com/19621113/69803140-4e30da80-11ec-11ea-91ac-a4da6b879a36.png)

_Originally posted by @Nelliza in https://github.com/DaRkLoL1/Fullstack-Development-2-task/issues/16#issuecomment-559459464_

**Comment by Nelliza** [comment]
![6](https://user-images.githubusercontent.com/19621113/69803671-cea40b00-11ed-11ea-82c1-955ce849318c.png)
Эти кнопки - не просто элемент декора, они предназначены для перехода на соответствующие аккаунты в соцсетях и поэтому тоже должны быть реализованы ссылками

**Comment by DaRkLoL1** [comment]
![](https://user-images.githubusercontent.com/19621113/69803671-cea40b00-11ed-11ea-82c1-955ce849318c.png)
Куда они должны ссылаться? Что за аккаунты?

**Comment by Nelliza** [comment]
Можно просто на главные страницы соцсетей, во всяком случае, я так реализовывала

**Comment by DaRkLoL1** [comment]
![Скриншот 2019-11-28 20_41_51](https://user-images.githubusercontent.com/32780725/69825225-93223480-121f-11ea-8876-7d6d5bbecfdb.png)
это вроде не ссылка, а кнопка отправки формы

**Comment by Nelliza** [comment]
> ![Скриншот 2019-11-28 20_41_51](https://user-images.githubusercontent.com/32780725/69825225-93223480-121f-11ea-8876-7d6d5bbecfdb.png)
> это вроде не ссылка, а кнопка отправки формы
Согласна ) В таком случае можно в атрибуте action формы указать URL-адрес, на который должна вести твоя "кнопка-ссылка"

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/69906098-2e0d4100-13cf-11ea-9cb6-04dce7c84d4a.png)
Вот здесь чуть не соглашусь: теоретически у тебя может быть не ссылка, а кнопка с размером `medium`, например, на другой странице (компоненты ведь являются переиспользуемыми). Здесь логичнее было бы в качестве условия отталкиваться от наличия содержимого у параметра `page`, ведь если мы передаем адрес страницы, мы подразумеваем, что это ссылка, а не кнопка

**Comment by Nelliza** [comment]
> ![6](https://user-images.githubusercontent.com/19621113/69803671-cea40b00-11ed-11ea-82c1-955ce849318c.png)
> Эти кнопки - не просто элемент декора, они предназначены для перехода на соответствующие аккаунты в соцсетях и поэтому тоже должны быть реализованы ссылками

Для ссылок, ведущих на внешние сайты, следует добавлять атрибут `rel="noopener noreferrer"`. Это связано с уязвимостью, об этом написано в [п.16 наших html-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md)

**Comment by DaRkLoL1** [comment]
Может кнопку прост ссылкой оборачивать и вернуть кнопку как было?

**Comment by Nelliza** [comment]
Не-не, согласно спецификации `HTML5` такое оборачивание является невалидным, вот [здесь](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) посмотри )

**Comment by Nelliza** [comment]
> Может кнопку прост ссылкой оборачивать и вернуть кнопку как было?

Не-не, согласно спецификации HTML5 такое оборачивание является невалидным, вот [здесь](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) посмотри )

**Comment by DaRkLoL1** [comment]
эх, ну ок((

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/71061414-fc3efd00-2178-11ea-9c26-6cc45885691b.png)
На данный момент в проекте отсутствует возможность быстрого перехода на главную страницу с внутренних страниц сайта. По идее вот этот логотип должен быть ссылкой на главную (ну кроме логотипа на главной, но это холиварный вопрос скорее, здесь думаю вполне уместно реализовать везде ссылкой)
