### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#31]
Не везде указаны запасной шрифт и запасное семейство:

**button.scss**
![1](https://user-images.githubusercontent.com/19621113/69906339-1932ac80-13d3-11ea-89b0-2f64aca88475.png)

**header.scss**
![2](https://user-images.githubusercontent.com/19621113/69906396-b42b8680-13d3-11ea-9c12-d8945eacfc0d.png)

**room.scss**
![3](https://user-images.githubusercontent.com/19621113/69906401-bbeb2b00-13d3-11ea-92b3-3e0fea5de6e4.png)

**Comment by DaRkLoL1** [comment]
Сделал, только зачем это? Это же прост штриховые картинки

**Comment by Nelliza** [comment]
А, ок, не обратила внимания )
