### ISSUE TITLE
Обработчики событий

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#32]
Все обработчики событий следует вынести в отдельные функции.
Кроме того, по стандартам рекомендуется также именовать обработчики для того, чтобы впоследствии можно было удалить их по имени

**Comment by Nelliza** [comment]
Имелось в виду именование такого вида:
>5. **Обработчики событий всегда именовать**;
>   ```javascript
>    // Надо не просто делать
>    $(window).scroll(...);
>    // а
>    $(window).on('scroll.myComponent', function (event) {...});
>   ```

**Comment by DaRkLoL1** [comment]
хм, а то что я сделал оставить?

**Comment by Nelliza** [comment]
Конечно, то, что ты сделал, также нужно по стандартам )
Имеется в виду дополнить вот этой частью:
> ```javascript
> $(window).on('scroll.myComponent', ...);
> ```

**Comment by DaRkLoL1** [comment]
Хорошо, а myComponent это что, бем-элемент или прост рандомное название, от чего отталкиваться при выборе имени?

**Comment by Nelliza** [comment]
Я отталкивалась от названия БЭМ-элемента + его индекса в псевдомассиве `NodeList` (полученном в результате выполнения этого кода: `document.querySelectorAll('.js-calendar')`), при этом индекс передавала в конструктор класса при создании его инстанса.

Индекс нужен для соблюдения требования об уникальности имен, прописанного здесь:
> * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть уникальными, чтобы $(block).off(...) отключал события только для текущего инстанса блока, не для всех инстансов, а то неожиданно для разработчика сразу будут отключены обработчики события для всех слайдеров на странице;

Но скорее всего возможны и другие варианты задания уникального имени, можешь реализовать на свое усмотрение )

**Comment by Nelliza** [comment]
В **expandable-checkbox-list.js** и **radio-buttons.js** не добавил индексы, и `querySelector` в инициализации не очень уместен, т.к. теоретически этих элементов может быть несколько
