### ISSUE TITLE
Именование обработчиков событий

### ISSUE THREAD

**Issue by Nelliza** [DaRkLoL1/Fullstack-Development-2-task#33]
**calendar.js**

Функции-обработчики событий для БЭМ-элементов именуются по шаблону `handleElementNameEventName`, где `ElementName` - имя БЭМ-элемента, исправь пожалуйста в некоторых методах в этой части:

- `$left`, `$right`, `$clear`, `$apply` - по-моему, не слишком удачные имена для переменных )
- `$left` и `$right`: во-первых, непонятно, к чему привязывается направление (неочевидно, что это поля ввода), а во-вторых, если поля поменять местами, придется переименовывать переменные. Предлагаю названия `$arrivalField` и `$departureField` соответственно; то же касается имен классов эти элементов
- `$clear` и `$apply`: также неясен контекст, предлагаю заменить на `$clearButton` и `$applyButton` соответственно

**Comment by DaRkLoL1** [comment]
Например для 
`const $clear = this.$datepicker.find('.js-calendar__clear-button');`
будет handleCalendar__clear-buttonClick чтоль или как?

**Comment by Nelliza** [comment]
Нет, `handleClearButtonClick` будет достаточно, думаю ) В JS же у нас используется `camelCase`, и имя БЭМ-элемента также преобразуется в этот формат

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/70832639-a7148b80-1e06-11ea-84c2-bfa71044d4a6.png)
Зачем тебе два одинаковых метода? Если в рамках соответствия ишью #32, то там уникальность имени требуется для `namespace` самого события, а не для функции-обработчика. Т.е. в этом случае можно повесить на оба события одну функцию с общим названием `handleDatepickerClick`, например

**Comment by Nelliza** [comment]
**calendar.js**
![1](https://user-images.githubusercontent.com/19621113/71058326-820a7a80-2170-11ea-8165-9e1c6b68db2d.png)

Здесь я думаю правильнее указывать не цифровые обозначения в значении модификатора, а более абстрактные (`small`, `medium`, `large`, `big`), т.к. если ты в будущем захочешь изменить ширину у этих блоков, придется менять также и название класса для них
