### ISSUE TITLE
Автоимпорт

### ISSUE THREAD

**Issue by performanceArtist** [DaRkLoL1/Fullstack-Development-2-task#4]
У webpack есть возможность импорта всех scss, js, png и прочих файлов - посмотри в документации. У тебя сейчас куча файлов только для импортов.

**Comment by DaRkLoL1** [comment]
Ты имеешь ввиду CopyWebpackPlugin чтоль или что?

**Comment by performanceArtist** [comment]
Нет, у самого webpack, [здесь](https://webpack.js.org/guides/dependency-management/#context-module-api).

**Comment by DaRkLoL1** [comment]
пытался я так подключать не фига не работает((

**Comment by performanceArtist** [comment]
Значит неправильно что-то делаешь. Конкретно у тебя сейчас даже entry нет в конфиге, в котором и должен быть автоимпорт - его достаточно указать один раз.

**Comment by DaRkLoL1** [comment]
entry в конфиге у меня в самом низу страницы

**Comment by performanceArtist** [comment]
По-моему не нужно столько entry-сборок, если у тебя нет какого-то уникального кода для страниц. Тем более у тебя они никак не разбиваются и куча кода повторяется из файла в файл. Сделай с одним. Или если всё-таки надо, можно добавить splitChunks в конфиг, но смысла большого нет.
